### ISSUE TITLE
关于MLS算法生成表面

### ISSUE THREAD

**Issue by Gatsby23** [loopvoid/mls#1]
您好， 不好意思，我想问下，现在我有一组点云，我想通过MLS算法生成Surface应该怎么做呢？像您blog中的效果，如下图所示
![image](https://user-images.githubusercontent.com/18000675/88511957-56aa1100-d018-11ea-857e-ec363acfb253.png)
是直接通过您的CPP代码可以实现还是说需要再进行其他操作呢？

**Comment by loopvoid** [comment]
MLS的目的在于根据已有的点，拟合出一个局部曲面方程。有了局部曲面方程，至于你怎么生成曲面的图形图像，这个方法就很多了吧。我的CPP主要是用拟合的局部曲面方程，来做一个局部滤波的作用。

**Comment by Gatsby23** [comment]
不好意思，这里我还是有点不清楚，方便加您个微信讨论一下么？

**Comment by Gatsby23** [comment]
> MLS的目的在于根据已有的点，拟合出一个局部曲面方程。有了局部曲面方程，至于你怎么生成曲面的图形图像，这个方法就很多了吧。我的CPP主要是用拟合的局部曲面方程，来做一个局部滤波的作用。

不好意思，这里我可能理解有点问题，这里应该相当于对空间中点云中的点进行调整？然后使他们符合某个表面方程？显示的话，就是各种构建Mesh的算法，然后可视化？

**Comment by loopvoid** [comment]
对的，是这个意思。不是很多库都有对点云建Mesh可视化的函数么，都可以使用的。

**Comment by Gatsby23** [comment]
哦哦，因为我主要做SLAM，对图形学这块不熟，多谢您耐心解答， 谢谢

**Comment by loopvoid** [comment]
MLS的目的在于根据已有的点，拟合一个局部曲面方程。有了曲面方程，至于你怎么生成曲面的图形图像，这个方法就很多了吧。

发送自 Windows 10 版邮件应用

发件人: Robotics_Qi
发送时间: 2020年7月27日 14:50
收件人: loopvoid/mls
抄送: Subscribed
主题: [loopvoid/mls] 关于MLS算法生成表面 (#1)

您好， 不好意思，我想问下，现在我有一组点云，我想通过MLS算法生成Surface应该怎么做呢？像您blog中的效果，如下图所示

是直接通过您的CPP代码可以实现还是说需要再进行其他操作呢？
